build: fix compiler warning about duplicate const specifier
clang warns:

    make[4]: Entering directory `./network-manager-applet/src'
      CC       nm_applet-ap-menu-item.o
    ap-menu-item.c:188:7: error: duplicate 'const' declaration specifier [-Werror,-Wduplicate-decl-specifier]
    const const char *
          ^~~~~~

Signed-off-by: Thomas Haller <thaller@redhat.com>
(cherry picked from commit 990afe4fd86fc9f304641b521d25430db8e2b16f)