applet: set proper notification hint
Commit f9023a0c242cd5f8ebcf999c57def5b7240e2299 broke the build:

applet.c:939:2: error: passing argument 3 of
‘notify_notification_set_hint’ from incompatible pointer type [-Werror]