build: fix typo in inclusion guard
clang warns:

    make[4]: Entering directory `./network-manager-applet/src'
      CC       nm_applet-applet.o
    In file included from applet.c:88:
    ./applet-vpn-request.h:23:9: error: 'APPLET_VPN_REQEUST_H' is used as a header guard here, followed by #define of a different macro [-Werror,-Wheader-guard]
    #ifndef APPLET_VPN_REQEUST_H
            ^~~~~~~~~~~~~~~~~~~~
    ./applet-vpn-request.h:24:9: note: 'APPLET_VPN_REQUEST_H' is defined here; did you mean 'APPLET_VPN_REQEUST_H'?
    #define APPLET_VPN_REQUEST_H
            ^~~~~~~~~~~~~~~~~~~~
            APPLET_VPN_REQEUST_H

Signed-off-by: Thomas Haller <thaller@redhat.com>
(cherry picked from commit de47edb1cc4433bfa224e907f3cf12b2e2fa72b8)