c-e: fix passing wrong enum type to gtk_widget_override_background_color()
This had no real effect, because both GTK_STATE_NORMAL
and GTK_STATE_FLAG_NORMAL have the numerical value 0.

clang warns:
    make[5]: Entering directory `./network-manager-applet/src/connection-editor'
      CC       nm_connection_editor-page-ip4.o
    page-ip4.c:730:63: error: implicit conversion from enumeration type 'GtkStateType' to different enumeration type 'GtkStateFlags' [-Werror,-Wenum-conversion]
            gtk_widget_override_background_color (GTK_WIDGET (editable), GTK_STATE_NORMAL, &rgba);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                         ^~~~~~~~~~~~~~~~

Signed-off-by: Thomas Haller <thaller@redhat.com>
(cherry picked from commit 3fc750af4624dbc74290513f41bd9c0ea21c6853)